In [1]:
import random 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from IPython.display import display
from sklearn.cluster import KMeans 
from sklearn.decomposition import PCA
from sklearn.metrics import homogeneity_score, completeness_score, \
v_measure_score, adjusted_rand_score, adjusted_mutual_info_score, silhouette_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("./[Dataset]_Module_36_(iris).data",header=None)
names = ["sepal_length", "sepal_width","petal_length", "petal_width", "class"]
df.columns = names
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
def Performance_output(data_frame, y_clust, labels, inertia) :
    df = pd.DataFrame({'clust_label': y_clust, 'orig_label': labels})
    ct = pd.crosstab(df['clust_label'], df['orig_label'])
    display(ct)
    print('% 9s' % 'inertia  homo    compl   v-meas   ARI     AMI     silhouette')
    print('%i       %.3f   %.3f   %.3f   %.3f   %.3f    %.3f'
      %(inertia,
      homogeneity_score(labels, y_clust),
      completeness_score(labels, y_clust),
      v_measure_score(labels, y_clust),
      adjusted_rand_score(labels, y_clust),
      adjusted_mutual_info_score(labels, y_clust),
      silhouette_score(data_frame, y_clust, metric='euclidean')))#statistics for clusters

K-Means()로 각종 지표값 출력

In [4]:
Data = df[["sepal_length", "sepal_width","petal_length", "petal_width"]]
labels = df['class']

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  # KMeans 객체 생성
kmeans.fit(Data)  # KMeans 모델 훈련
y_clust = kmeans.predict(Data)
Performance_output(Data, y_clust, labels, kmeans.inertia_)

orig_label   Iris-setosa  Iris-versicolor  Iris-virginica
clust_label
0                     50                0               0
1                      0               48              14
2                      0                2              36

inertia  homo    compl   v-meas   ARI     AMI     silhouette
78       0.751   0.765   0.758   0.730   0.755    0.553

In [5]:
def pca_transform(n_comp, data_frame):
    pca = PCA(n_components=n_comp)
    return pca.fit_transform(data_frame)

In [6]:
#3차원
Data_reduced = pca_transform(n_comp=3, data_frame=Data)
#print('Reduced Data \n', Data_reduced)

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  
kmeans.fit(Data_reduced)  
y_clust = kmeans.predict(Data_reduced)
Performance_output(Data_reduced, y_clust, labels, kmeans.inertia_)

orig_label   Iris-setosa  Iris-versicolor  Iris-virginica
clust_label
0                     50                0               0
1                      0               48              14
2                      0                2              36

inertia  homo    compl   v-meas   ARI     AMI     silhouette
75       0.751   0.765   0.758   0.730   0.755    0.563

In [7]:
#2차원
Data_reduced = pca_transform(n_comp=2, data_frame=Data)
#print('Reduced Data \n', Data_reduced)

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  
kmeans.fit(Data_reduced)  
y_clust = kmeans.predict(Data_reduced)
Performance_output(Data_reduced, y_clust, labels, kmeans.inertia_)

orig_label   Iris-setosa  Iris-versicolor  Iris-virginica
clust_label
0                      0                3              36
1                      0               47              14
2                     50                0               0

inertia  homo    compl   v-meas   ARI     AMI     silhouette
63       0.736   0.747   0.742   0.716   0.739    0.598

In [8]:
#1차원
Data_reduced = pca_transform(n_comp=1, data_frame=Data)
#print('Reduced Data \n', Data_reduced)

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  
kmeans.fit(Data_reduced)  
y_clust = kmeans.predict(Data_reduced)
Performance_output(Data_reduced, y_clust, labels, kmeans.inertia_)

orig_label   Iris-setosa  Iris-versicolor  Iris-virginica
clust_label
0                      0                1              38
1                      0               49              12
2                     50                0               0

inertia  homo    compl   v-meas   ARI     AMI     silhouette
37       0.788   0.800   0.794   0.773   0.792    0.677

n_comp 매개변수로 분산 비율의 목표를 전달할 수 있습니다. 예를 들어, n_comp=0.95로 설정되면, PCA는 데이터셋의 분산의 95%를 보존하는 주성분 수를 찾습니다. 즉, 반환된 주성분은 원래 데이터의 95% 이상의 분산을 설명할 수 있어야 합니다. 리턴값은 달성된 주성분의 수가 됩니다.

In [9]:
# 분산 비율의 목표치
Data_reduced = pca_transform(n_comp=0.95, data_frame=Data)
print('Reduced Data \n', Data_reduced[:10])

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  
kmeans.fit(Data_reduced)  
y_clust = kmeans.predict(Data_reduced)
Performance_output(Data_reduced, y_clust, labels, kmeans.inertia_)

Reduced Data
 [[-2.68420713  0.32660731]
 [-2.71539062 -0.16955685]
 [-2.88981954 -0.13734561]
 [-2.7464372  -0.31112432]
 [-2.72859298  0.33392456]
 [-2.27989736  0.74778271]
 [-2.82089068 -0.08210451]
 [-2.62648199  0.17040535]
 [-2.88795857 -0.57079803]
 [-2.67384469 -0.1066917 ]]

orig_label   Iris-setosa  Iris-versicolor  Iris-virginica
clust_label
0                      0                3              36
1                      0               47              14
2                     50                0               0

inertia  homo    compl   v-meas   ARI     AMI     silhouette
63       0.736   0.747   0.742   0.716   0.739    0.598

**시간 측정**

In [11]:
import time

s_time = time.time()

k = 3
kmeans = KMeans(n_clusters=k, init='random', random_state=0)
for  _ in range(10) :
    kmeans.fit(Data)  # KMeans 모델 훈련

print('Elapsed time :', time.time() - s_time)

Elapsed time : 2.066974401473999

In [13]:
#1차원
Data_reduced = pca_transform(n_comp=1, data_frame=Data)

k = 3
s_time = time.time()
kmeans = KMeans(n_clusters=k, init='random', random_state=0)  
for  _ in range(10) :
    kmeans.fit(Data_reduced)  

print('Elapsed time :', time.time() - s_time)

Elapsed time : 2.1177785396575928

In [14]:
print(Data)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [15]:
print(Data_reduced)

[[-2.68420713]
 [-2.71539062]
 [-2.88981954]
 [-2.7464372 ]
 [-2.72859298]
 [-2.27989736]
 [-2.82089068]
 [-2.62648199]
 [-2.88795857]
 [-2.67384469]
 [-2.50652679]
 [-2.61314272]
 [-2.78743398]
 [-3.22520045]
 [-2.64354322]
 [-2.38386932]
 [-2.6225262 ]
 [-2.64832273]
 [-2.19907796]
 [-2.58734619]
 [-2.3105317 ]
 [-2.54323491]
 [-3.21585769]
 [-2.30312854]
 [-2.35617109]
 [-2.50791723]
 [-2.469056  ]
 [-2.56239095]
 [-2.63982127]
 [-2.63284791]
 [-2.58846205]
 [-2.41007734]
 [-2.64763667]
 [-2.59715948]
 [-2.67384469]
 [-2.86699985]
 [-2.62522846]
 [-2.67384469]
 [-2.98184266]
 [-2.59032303]
 [-2.77013891]
 [-2.85221108]
 [-2.99829644]
 [-2.4055141 ]
 [-2.20883295]
 [-2.71566519]
 [-2.53757337]
 [-2.8403213 ]
 [-2.54268576]
 [-2.70391231]
 [ 1.28479459]
 [ 0.93241075]
 [ 1.46406132]
 [ 0.18096721]
 [ 1.08713449]
 [ 0.64043675]
 [ 1.09522371]
 [-0.75146714]
 [ 1.04329778]
 [-0.01019007]
 [-0.5110862 ]
 [ 0.51109806]
 [ 0.26233576]
 [ 0.98404455]
 [-0.174864  ]
 [ 0.92757294]
 [ 0.65959279]
 [ 0.23454059]
 [ 0.94236171]
 [ 0.0432464 ]
 [ 1.11624072]
 [ 0.35678657]
 [ 1.29646885]
 [ 0.92050265]
 [ 0.71400821]
 [ 0.89964086]
 [ 1.33104142]
 [ 1.55739627]
 [ 0.81245555]
 [-0.30733476]
 [-0.07034289]
 [-0.19188449]
 [ 0.13499495]
 [ 1.37873698]
 [ 0.58727485]
 [ 0.8072055 ]
 [ 1.22042897]
 [ 0.81286779]
 [ 0.24519516]
 [ 0.16451343]
 [ 0.46303099]
 [ 0.89016045]
 [ 0.22887905]
 [-0.70708128]
 [ 0.35553304]
 [ 0.33112695]
 [ 0.37523823]
 [ 0.64169028]
 [-0.90846333]
 [ 0.29780791]
 [ 2.53172698]
 [ 1.41407223]
 [ 2.61648461]
 [ 1.97081495]
 [ 2.34975798]
 [ 3.39687992]
 [ 0.51938325]
 [ 2.9320051 ]
 [ 2.31967279]
 [ 2.91813423]
 [ 1.66193495]
 [ 1.80234045]
 [ 2.16537886]
 [ 1.34459422]
 [ 1.5852673 ]
 [ 1.90474358]
 [ 1.94924878]
 [ 3.48876538]
 [ 3.79468686]
 [ 1.29832982]
 [ 2.42816726]
 [ 1.19809737]
 [ 3.49926548]
 [ 1.38766825]
 [ 2.27585365]
 [ 2.61419383]
 [ 1.25762518]
 [ 1.29066965]
 [ 2.12285398]
 [ 2.3875644 ]
 [ 2.84096093]
 [ 3.2323429 ]
 [ 2.15873837]
 [ 1.4431026 ]
 [ 1.77964011]
 [ 3.07652162]
 [ 2.14498686]
 [ 1.90486293]
 [ 1.16885347]
 [ 2.10765373]
 [ 2.31430339]
 [ 1.92245088]
 [ 1.41407223]
 [ 2.56332271]
 [ 2.41939122]
 [ 1.94401705]
 [ 1.52566363]
 [ 1.76404594]
 [ 1.90162908]
 [ 1.38966613]]